/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.36).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-12-30T12:05:52.189Z[GMT]")
@Validated
public interface UserApi {

    @Operation(summary = "Get all user info if you are an employee", description = "get all user info in an array", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "user" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "succesfully loaded users", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = User.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter"),
        
        @ApiResponse(responseCode = "401", description = "only employees are allowed to load all user info") })
    @RequestMapping(value = "/users",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<UserResponseDTO>> getAllUserInfo(
            @Parameter(in = ParameterIn.QUERY, description = "Set the parameter to true to obtain an array of users without bankaccounts" ,schema=@Schema()) @Valid
            @RequestParam(value = "onlyWithoutBankAccounts", required = false) Boolean onlyWithoutBankAccounts);

    @Operation(summary = "get your own user info", description = "get your own user info", security = {
            @SecurityRequirement(name = "bearerAuth")    }, tags={ "user" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "succesfully loaded your own user", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = User.class)))),

            @ApiResponse(responseCode = "400", description = "bad input parameter"),

            @ApiResponse(responseCode = "401", description = "not allowed to load users") })
    @RequestMapping(value = "/user",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<UserResponseDTO>> getUserInfo();

    @Operation(summary = "get user info by user id", description = "load all user info by user id", tags={ "user" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "succesfully loaded the user info", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = User.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter"),
        
        @ApiResponse(responseCode = "401", description = "not allowed to register") })
    @RequestMapping(value = "/user/{userId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<UserResponseDTO>> getUserInfoById(@Parameter(in = ParameterIn.PATH, description = "the user id of whom information has to be loaded", required=true, schema=@Schema()) @PathVariable("userId") Integer userId);


    @Operation(summary = "register a new user as customer", description = "register a new customer banking user account to gain access to the banking application", tags={ "user" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "succesfully registered as a new user", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = User.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter")
    })

    @RequestMapping(value = "/user/register",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<UserResponseDTO>> postRegisterUser(@Parameter(in = ParameterIn.DEFAULT, description = "new user body for registering the user", required=true, schema=@Schema()) @Valid @RequestBody NewUserRequestDTO body);


    @Operation(summary = "register a new user performed by an employee", description = "this endpoint can only be used by an employee, and this employee can register a new user and also his/her userType", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "user" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "succesfully created a new user", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = User.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter"),
        
        @ApiResponse(responseCode = "401", description = "not allowed to register user") })
    @RequestMapping(value = "/user",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<UserResponseDTO>> postUser(@Parameter(in = ParameterIn.DEFAULT, description = "new user body for registering the user", required=true, schema=@Schema()) @Valid @RequestBody NewUserEmployeeRequestDTO body);


    @Operation(summary = "update user info", description = "update user info by the info delivered in the requestbody, <b>*<u>leave a value empty to keep the default value</u></b>", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "user" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "succesfully updated the user", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = User.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter"),
        
        @ApiResponse(responseCode = "401", description = "not allowed to update this user info") })
    @RequestMapping(value = "/user",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<List<UserResponseDTO>> putUser(@Parameter(in = ParameterIn.DEFAULT, description = "updated info for this user", required=true, schema=@Schema()) @Valid @RequestBody UpdateUserRequestDTO body);


    @Operation(summary = "Endpoint for recieving a JWT token", description = "Send the correct credentials within the requestbody to recieve a JWT token ", tags={ "user" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "succesfully logged in", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LoginResponseDTO.class)))),
        
        @ApiResponse(responseCode = "400", description = "Incorrect credentials"),
        
        @ApiResponse(responseCode = "401", description = "not allowed") })
    @RequestMapping(value = "/user/login",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<LoginResponseDTO>> userLogin(@Parameter(in = ParameterIn.DEFAULT, description = "required login info", required=true, schema=@Schema()) @Valid @RequestBody LoginRequestDTO body);

}

